= Hazelcast IMDG Documentation
// Settings:
ifdef::env-github[]
:warning-caption: :warning:
endif::[]
// URLs:
:url-org: https://github.com/JakeSCahill
:url-contribute: https://github.com/JakeSCahill/hazelcast-docs/blob/develop/.github/CONTRIBUTING.adoc
:url-ui: {url-org}/hazelcast-docs-ui
:url-playbook: {url-org}/hazelcast-docs

This repository contains the Antora components for the Hazelcast IMDG documentation.

The documentation source files are marked up with AsciiDoc.

== Docs Structure

This section describes some important information about how this repository is structured:

- The component name, version, and start page are configured in each branch's `antora.yml` file.
- The navigation for all modules is stored in the ROOT module's `nav.adoc` file.
- Production branches use the *vX.Y* naming pattern (for example, v4.1), and the `master` branch contains the latest content.
- The {url-playbook}[docs site playbook] instructs Antora to automatically aggregate content in the `master` branch as well as any branch names that start with *v*.

== GitHub Actions

To automate some elements of the build process, this repository includes the following GitHub Actions:

.GitHub Actions
[cols="m,a,a"]
|===
|File |Description |Triggers

|validate-site.yml
|Validates that all internal links are working
|On a pull request to the `master` branch as well as any branch names that start with *v*

|build-staging.yml
|Builds the staging documentation site by sending a build hook to Netlify (the hosting platform that we use)
|On a pull request or a push to the `master` branch as well as any branch names that start with *v*

|build-site.yml
|Builds the production documentation site by sending a build hook to Netlify (the hosting platform that we use)
|On a push to the `master` branch as well as any branch names that start with *v*
|===

== Contributing

If you want to add a change or contribute new content, see our {url-contribute}[contributing guide].

To let us know about something that you'd like us to change, consider {url-org}/hazelcast-reference-manual/issues/new[creating an issue].
