= Hazelcast IMDG Documentation
// Settings:
ifdef::env-github[]
:warning-caption: :warning:
endif::[]
// URLs:
:url-org: https://github.com/hazelcast
:url-contribute: https://github.com/hazelcast/hazelcast-docs/blob/develop/.github/CONTRIBUTING.adoc
:url-ui: {url-org}/hazelcast-docs-ui
:url-playbook: {url-org}/hazelcast-docs
:url-staging: https://develop--nifty-wozniak-71a44b.netlify.app/home/index.html

This repository contains the Antora components for the Hazelcast IMDG documentation.

The documentation source files are marked up with AsciiDoc.

== Docs Structure

This section describes some important information about how this repository is structured:

- The component name, version, and start page are configured in each branch's `antora.yml` file.
- The navigation for all modules is stored in the ROOT module's `nav.adoc` file.
- The {url-playbook}[docs site playbook] instructs Antora to automatically build the site using content in the `master` branch as well as any tags that are prefixed with *v*.

== Release Workflow

Documentation for new releases is hosted in versioned tags that are prefixed with `v`. For example, content for the `4.1.1` version is hosted in the `v4.1.1` tag. The `latest-dev` content is stored in the `master` branch

The documentation build process is triggered whenever you push a new tag to this repository or commit to the `master` branch.

=== Patch Releases

This section guides you through the steps for releasing documentation for patch releases.

. Find the `.z` branch for your version. For example, if you're working on content for version 4.1.2, find the branch named `4.1.z`.
+
TIP: For guidance on writing content, see the {url-contribute}[contribution guidelines].
+
NOTE: If a branch for your major or minor version does not exist, see <<major-and-minor-releases, Major and Minor Releases>>.

. When you are ready to release, create a new release branch from the `.z` branch and name it with the full version number that you are releasing. For example, if you are releasing version 4.1.2, name the branch 4.1.2.

. In the `antora.yml` file of your release branch, update the `version` field with the version of IMDG that you are working on.  For example from `4.1.2-SNAPSHOT` to `4.1.2`.
+
[source,yaml]
----
version: 4.1.2
----

. Tag the latest commit in your release branch with a `v` followed by the version number.

. If you have made any changes since creating your release branch, merge those changes back into the `.z` branch.

. Delete your release branch.
+
WARNING: Do not delete the `.z` branch. This branch is for writing content for future patch releases.

. In the `antora.yml` file of the `.z` branch, increment the `version` field. For example, `4.1.2-SNAPSHOT` becomes `4.1.3-SNAPSHOT`.

. If you are releasing a new latest version, in the `develop` branch of the `hazelcast/hazelcast-docs` repository, submit a pull request to update the `_redirects` file with your release version of IMDG.
+
NOTE: This file is where we alias the `latest` path in URLs.
+
[source,bash]
----
# Redirect latest imdg alias to the latest version
/imdg/latest/*  /imdg/4.1.2/:splat 200!
----

The documentation site will now be built, including content from your tagged version.

== Major and Minor  Releases

This section guides you through the steps for releasing documentation for major and minor releases.

. Work on the content for a new Major or Minor release on the `master` branch (there is an exception - if you work on content for the new Minor branch which is lower than current Major version then you need to create `\{version\}.y` branch. For example if `5.0` was released and you plan to add content for `4.3` then you need to create `4.y` branch and work on it. Then use this branch in following text instead of `master` branch).
+
TIP: For guidance on writing content, see the {url-contribute}[contribution guidelines].

. When you are ready to release, create a new release branch from the `master` branch and name it with the full version number that you are releasing. For example, if you are releasing version 5.0, name the branch 5.0.

. If you are releasing a new `latest-dev` version, in the `antora.yml` file of the `master` branch, increment the `version` field to the `latest-dev` version. For example, `5.0-SNAPSHOT` becomes `5.1.0-SNAPSHOT`.

. In the `antora.yml` file of your release branch, update the `version` field with the version of IMDG that you are working on. For example from `5.0-SNAPSHOT` to `5.0`.
+
[source,yaml]
----
version: 5.0
----

. Tag the latest commit in your release branch with a `v` followed by the version number.

. Create a `\{version\}.z` branch from release branch. It ensures that all changes made since creating your release branch will be applied to the new `.z` branch. For example `5.0.z` branch.

. Delete your release branch.
+
WARNING: Do not delete the `.z` branch. This branch is for writing content for future patch releases.

. In the `antora.yml` file of the `.z` branch, increment the `version` field. For example, `5.0` becomes `5.0.1-SNAPSHOT`.

. In the `develop` branch of the `hazelcast/hazelcast-docs` repository, submit a pull request to update the `_redirects` file with the new versions of IMDG.
+
NOTE: This file is where we alias the `latest-dev` and `latest` paths in URLs.
+
[source,bash]
----
# Redirect latest imdg alias to the latest version
/imdg/latest/*  /imdg/5.0/:splat 200!
# Redirect latest-dev imdg alias to the latest-dev version
/imdg/latest-dev/*  /imdg/5.1-snapshot/:splat 200!
----

The documentation site will now be built, including content from your tagged version.

== GitHub Actions

To automate some elements of the build process, this repository includes the following GitHub Actions:

.GitHub Actions
[cols="m,a,a"]
|===
|File |Description |Triggers

|validate-site.yml
|Validates that all internal and external links are working
|On a pull request to the `master`, `archive`, and `*.z` branches

|build-staging.yml
|Builds the staging documentation site by sending a build hook to Netlify (the hosting platform that we use)
|On a pull request to the `master`, `archive`, and `*.z` branches

|build-site.yml
|Builds the production documentation site by sending a build hook to Netlify (the hosting platform that we use)
|On a push to the `master` branch and any tags whose names start with `v`
|===

== Contributing

If you want to add a change or contribute new content, see our {url-contribute}[contributing guide].

To let us know about something that you'd like us to change, consider {url-org}/hazelcast-reference-manual/issues/new[creating an issue].
