= Event Listeners for Hazelcast Clients

You can add event listeners to Hazelcast clients.
You can configure the following listeners to listen to the events
on the client side:

* xref:cluster-events.adoc#listening-for-lifecycle-events[Lifecycle Listener]: Notifies
when the client is starting, started, shutting down and shutdown.
* xref:cluster-events.adoc#listening-for-member-events[Membership Listener]: Notifies when
a member joins to/leaves the cluster to which the client is connected,
or when an attribute is changed in a member.
* xref:cluster-events.adoc#listening-for-distributed-object-events[Distributed Object Listener]:
Notifies when a distributed object is created or destroyed throughout
the cluster to which the client is connected. Also notifies for the events
happening in the distributed data structures, e.g., entry, item and message
listeners.

For Hazelcast Java client example code/configuration snippets, see the
sections of the current chapter, i.e., xref:distributed-events.adoc[Distributed Events].
See also the xref:clients:java.adoc#configuring-client-listeners[Configuring Client Listeners section]
for more information.

Follow the below links to learn how to configure the event listeners on other
Hazelcast clients:

* http://hazelcast.github.io/hazelcast-csharp-client/4.1.0/doc/events.html[.NET client^]
* https://github.com/hazelcast/hazelcast-cpp-client/blob/master/Reference_Manual.md#75-distributed-events[C++ client^]
* https://github.com/hazelcast/hazelcast-nodejs-client/blob/master/DOCUMENTATION.md#85-distributed-events[Node.js client^]
* https://hazelcast.readthedocs.io/en/stable/using_python_client_with_hazelcast_imdg.html#distributed-events[Python client^]
* https://github.com/hazelcast/hazelcast-go-client#75-distributed-events[Go client^]

Note that you can simply add a listener to your client that you already configured
and registered on the member side. You do not need to configure the listener on the client.
In the following example, the member side has implemented the listener `MyListener`. To run that listener on the client, use `addEntryListener` in your client codee. 

[tabs] 
==== 
Java:: 
+ 
--
[source,java]
----
IMap<Object, Object> map = client.getMap("mymap");
map.addEntryListener(new MyListener(), true);
----
--
C++:: 
+
--
[source,cpp]
----


----
--

C Sharp:: 
+
-- 
[source,cs]
----

----
--

Node.js:: 
+ 
-- 
[source,javascript]
----

----
--
Python:: 
+ 
-- 
[source,python]
----

----
--
Go:: 
+ 
-- 
[source,go]
----

----
--
====

As you see, no configuration is needed.