= Kubernetes/OpenShift Deployment
[[deploying-in-kubernetes]]

Hazelcast provides a few methods to simplify deploying Hazelcast cluster into Kubernetes-based environments. For production-grade Kubernetes deployment, use Helm chart or Kubernetes/OpenShift Operator.

== Quick Start

If you just want to play with Hazelcast on Kubernetes, execute the following commands to create Hazelcast cluster
with 3 members into `default` namespace using the `default` Service Account.

[source,shell]
----
kubectl apply -f https://raw.githubusercontent.com/hazelcast/hazelcast-kubernetes/master/rbac.yaml
kubectl run hazelcast-1 --image=hazelcast/hazelcast:$HAZELCAST_VERSION
kubectl run hazelcast-2 --image=hazelcast/hazelcast:$HAZELCAST_VERSION
kubectl run hazelcast-3 --image=hazelcast/hazelcast:$HAZELCAST_VERSION
----

Hazelcast members automatically discovers themselves using the
https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes Discovery plugin^]
and therefore form one Hazelcast cluster.

== Helm Chart

https://helm.sh/[Helm^] is a package manager for Kubernetes. Hazelcast is distributed in a form of Helm Charts:

* https://github.com/hazelcast/charts/tree/master/stable/hazelcast[hazelcast/hazelcast^]
* https://github.com/hazelcast/charts/tree/master/stable/hazelcast-enterprise[hazelcast/hazelcast-enterprise^]

See the https://github.com/hazelcast/charts[Hazelcast Helm Charts documentation^]
for more details.
