= Download Archives
[[installing-using-download-archives]]

NOTE: As a prerequisite, make sure you have Java installed on your system.
If you're using JDK 11 or later, see xref:running-in-modular-java.adoc[].
For the list of supported Java versions, see xref:supported-jvms.adoc[].

You can download and install Hazelcast IMDG yourself. You only need to:

* download the package `hazelcast-{page-component-version}.zip` or `hazelcast-{page-component-version}.tar.gz`
from https://hazelcast.org/download[hazelcast.org^]
* extract the downloaded `hazelcast-{page-component-version}.zip` or `hazelcast-{page-component-version}.tar.gz`
* and add the file `hazelcast-{page-component-version}.jar` to your classpath.

When you download and extract the Hazelcast ZIP or TAR.GZ package, you will
see the `start/stop.sh` (for Linux) and `start/stop.bat` (for Windows) scripts under the `/bin` folder.
These scripts start/stop a Hazelcast member. See the xref:getting-started.adoc#creating-a-cluster[Quick Start chapter] to see the start scripts in action.

There are also some other scripts in the download archive whose usage descriptions
are given in their related sections including the <<using-the-script-cluster-sh, Using the Script cluster.sh>>,
<<cp-subsystem-management-apis, CP Subsystem Management APIs section>> and
<<health-check-script, Using the healthcheck.sh Script>> sections. You can also check the full list
of scripts in the `readme.html` of your download archive.