= Overriding the Built-in Serializers
:description: Hazelcast serializes basic data types such as `Byte` and `Boolean` using a built-in serializer. If you would prefer to implement your own serializer for these data types, you can overrise the built-in serializer.

{description}

For a complete list of data types that use the built-in serializer, see xref:serialization.adoc#data-types-with-built-in-serialization[].

WARNING: You should use this configuration cautiously. Built-in serializers are used heavily by the Hazelcast internally.  If any of the instances in a cluster overrides a built-in serializer, all the members and clients in that cluster must override it with the same serializer.

This configuration is specifically for the following cases:

- You implement a a custom serialization configuration by the user for a type
- Hazelcast adds a built-in serializer for the same type in a future release.

To be able to support rolling upgrade from an old version, you need to make sure of
the backward compatibility of the serialization. As a solution, you can set this property on
the new version so that the new instances can override the new built-in serializers with their
existing custom ones.

By default, you cannot override the built-in serializers. To enable this feature, configure your Hazelcast members with the following:

[tabs] 
==== 
XML:: 
+ 
--
This is an example of xref:configuration:configuring-declaratively.adoc[declarative configuration].

[source,xml]
----
<hazelcast>
    <serialization>
        <allow-override-default-serializers>true</allow-override-default-serializers>
    </serialization>
</hazelcast>
----
--

YAML::
+
--
This is an example of xref:configuration:configuring-declaratively.adoc[declarative configuration].

[source,xml]
----
hazelcast:
    serialization:
        allow-override-default-serializers: true
----
--

Java::
+
--
This is an example of xref:configuration:configuring-programmatically.adoc[programmatic configuration].

[source,java]
----
SerializationConfig{
  boolean isAllowOverrideDefaultSerializers();
 
  SerializationConfig setAllowOverrideDefaultSerializers(final boolean allowOverrideDefaultSerializers);}
----
--
====


