= REST Client
[[rest-client]]

Hazelcast provides a REST interface: it provides an HTTP service in each cluster member so that you can access your `map` and `queue` using HTTP protocol. Assuming `mapName` and `queueName` are already configured in your Hazelcast, its structure is shown below:

`+http://member IP address:port/hazelcast/rest/maps/mapName/key+`

`+http://member IP address:port/hazelcast/rest/queues/queueName+`

For the operations to be performed, standard REST conventions for HTTP calls are used.

NOTE: REST client request listener service is not enabled by default. You should enable it on your cluster members to use REST client. It can be enabled using the `DATA` endpoint group; see the xref:management:rest-endpoint-groups.adoc[Using the REST Endpoint Groups section].The previously used `hazelcast.rest.enabled` system property is deprecated.

NOTE: All parameters that are used in REST API URLs, such as the distributed data structure and key names, must be
https://en.wikipedia.org/wiki/Percent-encoding[URL encoded] when composing a call. As an example, `name.with/special@chars`
parameter value would be encoded as `name.with%2Fspecial%40chars`.

== REST Client GET/POST/DELETE Examples

In the following `GET`, `POST` and `DELETE` examples, assume that your cluster members are as shown below.

[source,plain]
----
Members [5] {
  Member [10.20.17.1:5701]
  Member [10.20.17.2:5701]
  Member [10.20.17.4:5701]
  Member [10.20.17.3:5701]
  Member [10.20.17.5:5701]
}
----

[NOTE]
====
All of the requests below can return one of the following responses in case of a failure.

* If the HTTP request syntax is not known, the following response is returned.
+
```
HTTP/1.1 400 Bad Request
Content-Length: 0
```
+
* In case of an unexpected exception, the following response is returned.
+
```
< HTTP/1.1 500 Internal Server Error
< Content-Length: 0
```
====

=== Creating/Updating Entries in a Map for REST Client

You can put a new `key1/value1` entry into a map by using `POST` call to
`+http://<member IP address>:<port>/hazelcast/rest/maps/mapName/key1+` URL.
This call's content body should contain the value of the key.
Also, if the call contains the MIME type, Hazelcast stores this information, too.

An example `POST` call is shown below.

[source,plain]
----
$ curl -v -X POST -H "Content-Type: text/plain" -d "bar"
    http://10.20.17.1:5701/hazelcast/rest/maps/mapName/foo
----

It returns the following response if successful:

[source,plain]
----
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 0
----

=== Retrieving Entries from a Map for REST Client

If you want to retrieve an entry, you can use a `GET` call
to `+http://<member IP address>:<port>/hazelcast/rest/maps/mapName/key1+`.
You can also retrieve this entry from another member of your cluster, such as
`+http://<another member IP address>:<port>/hazelcast/rest/maps/mapName/key1+`.

An example of a `GET` call is shown below.

```
curl -X GET http://<member IP address>:<port>/hazelcast/rest/maps/mapName/foo
```

It returns the following response if there is a corresponding value:

```
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 3
bar
```

This `GET` call returned a value, its length and also the MIME type
(`text/plain`) since the POST call example shown above included the MIME type.

It returns the following if there is no mapping for the given key:

[source,plain]
----
< HTTP/1.1 204 No Content
< Content-Length: 0
----

=== Removing Entries from a Map for REST Client

You can use a `DELETE` call to remove an entry. An example `DELETE` call is shown below with its response.

[source,plain]
----
$ curl -v -X DELETE http://10.20.17.1:5701/hazelcast/rest/maps/mapName/foo
----

```
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 0
```

If you leave the key empty as follows, the `DELETE` call deletes all entries from the map.

[source,plain]
----
$ curl -v -X DELETE http://10.20.17.1:5701/hazelcast/rest/maps/mapName
----

[source,plain]
----
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 0
----

=== Offering Items on a Queue for REST Client

You can use a `POST` call to create an item on the queue. An example is shown below.

[source,plain]
----
$ curl -v -X POST -H "Content-Type: text/plain" -d "foo"
    http://10.20.17.1:5701/hazelcast/rest/queues/myEvents
----

The above call is equivalent to `HazelcastInstance.getQueue("myEvents").offer("foo");`.

It returns the following if successful:

[source,plain]
----
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 0
----

It returns the following if the queue is full and the item is not able to be offered to the queue:

[source,plain]
----
< HTTP/1.1 503 Service Unavailable
< Content-Length: 0
----

=== Retrieving Items from a Queue for REST Client

You can use a `DELETE` call for retrieving items from a queue. Note that you should state the poll timeout while polling for queue events by an extra path parameter.

An example is shown below (**10** being the timeout value).

[source,plain]
----
$ curl -v -X DELETE \http://10.20.17.1:5701/hazelcast/rest/queues/myEvents/10
----

The above call is equivalent to `HazelcastInstance.getQueue("myEvents").poll(10, SECONDS);`. Below is the response.

[source,plain]
----
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 3
foo
----

When the timeout is reached, the response is `No Content` success, i.e., there is no item on the queue to be returned.

[source,plain]
----
< HTTP/1.1 204 No Content
< Content-Length: 0
----

=== Getting the size of the queue for REST Client

[source,plain]
----
$ curl -v -X GET \http://10.20.17.1:5701/hazelcast/rest/queues/myEvents/size
----

The above call is equivalent to `HazelcastInstance.getQueue("myEvents").size();`. Below is an example response.

[source,plain]
----
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 1
5
----

== Checking the Status of the Cluster for REST Client

Besides the above operations, you can check the status of your cluster, an example of which is shown below.

[source,plain]
----
$ curl -v http://127.0.0.1:5701/hazelcast/rest/cluster
----

The response is as follows:

[source,plain]
----
< HTTP/1.1 200 OK
< Content-Length: 119

Members [5] {
  Member [10.20.17.1:5701] this
  Member [10.20.17.2:5701]
  Member [10.20.17.4:5701]
  Member [10.20.17.3:5701]
  Member [10.20.17.5:5701]
}

ConnectionCount: 5
AllConnectionCount: 20
----

---

RESTful access is provided through any member of your cluster. You can even put an HTTP load-balancer in front of your cluster members for load balancing and fault tolerance.


NOTE: You need to handle the failures on REST polls as there is no transactional guarantee.