= ICountDownLatch
[[icountdownlatch]]

Hazelcast `ICountDownLatch` is the distributed implementation of `java.util.concurrent.CountDownLatch`.

NOTE: The original implementation of `ICountDownLatch ` has been deprecated. To read about the previous implementation, see the https://docs.hazelcast.org/docs/3.11.2/manual/html-single/index.html#icountdownlatch[ICountDownLatch] section of the Hazelcast IMDG 3.11 Reference Manual. The xref:cp-subsystem:cp-subsystem.adoc[CP Subsystem] introduces `ICountDownLatch ` provided by the *CP Subsystem*.

[[gate-keeping-concurrent-activities]]
== Gate-Keeping Concurrent Activities

`ICountDownLatch` is considered to be a gate keeper for concurrent activities.
It enables the threads to wait for other threads to complete their operations.
The following examples describe the mechanism of `ICountDownLatch`.

Assume that there is a leader process and there are follower processes that will
wait until the leader completes. Here is the leader:

[source,java]
----
include::{javasource}/dds/countdownlatch/Leader.java[tag=leader]
----

Since only a single step is needed to be completed as a sample, the above code
initializes the latch with 1. Then, the code sleeps for a while to simulate a
process and starts the countdown. Finally, it clears up the latch. Let's write a follower:

[source,java]
----
include::{javasource}/dds/countdownlatch/Follower.java[tag=follower]
----

The follower class above first retrieves `ICountDownLatch` and then calls the `await`
method to enable the thread to listen for the latch. The method `await` has a timeout
value as a parameter. This is useful when the `countDown` method fails. To see `ICountDownLatch`
in action, start the leader first and then start one or more followers. You will see that the
followers wait until the leader completes.

== Recovering From Failure

In a distributed environment, the counting down cluster member may go down. In this case, all listeners are notified immediately and automatically by Hazelcast. The state of the current process just before the failure should be verified and 'how to continue now' should be decided, e.g., restart all process operations, continue with the first failed process operation and throw an exception.

== Using ICountDownLatch

Although `ICountDownLatch` is a very useful synchronization aid, you may probably not use it on a daily basis. Unlike Java's implementation, Hazelcast's `ICountDownLatch` count can be reset after a countdown has finished, but not during an active count.