= Distributed Map
:description: Distributed maps, also known as maps or IMaps, are key-value pairs that are partitioned across a cluster. Use maps to distribute data across a cluster and make it easy to scale your applications while protecting data against member failures.
:url-cap-theorem: https://en.wikipedia.org/wiki/CAP_theorem
[[map]]

{description}

Distributed maps store values that you can access, using a unique key. These values can be objects as well as serialized data such as JSON values. For example, the following map stores the names of captial cities. The key is just an incrementing integer to make sure that each one is unique.

```
1. Tokyo
2. Paris
3. London
4. Ankara
5. Berlin
```

To distribute a map, Hazelcast uses the keys to partition them across the cluster. Each member in a cluster stores an almost equal partition size.
For example, if you have a map with 1000 entries on one member, then you start a second member, each member will store 500 entries. To learn more about how data is partitioned in a cluster, see xref:overview:data-partitioning.adoc[].

By default, all maps are backed up by one other member to avoid data loss. This way, if a member goes down, that member's partition is available on another.

In terms of the link:{url-cap-theorem}[CAP theorem], maps are ideal for applications that rely on data being _available_ rather than _consistent_. However, you can configure maps to xref:expiration-and-eviction.adoc[reduce the chances of data becoming stale].

== Learn More

Find out how to xref:creating-a-map.adoc[create a map] and write entries to it.