= Overview of Hazelcast Distributed Objects
[[overview-of-hazelcast-distributed-objects]]

Hazelcast has two types of distributed objects in terms of their partitioning strategies:

. Data structures where each partition stores a part of the instance,
namely partitioned data structures.
. Data structures where a single partition stores the whole instance,
namely non-partitioned data structures.

The following are the partitioned Hazelcast data structures:

* Map
* MultiMap
* Cache (Hazelcast JCache implementation)
* Event Journal

The following are the non-partitioned Hazelcast data structures:

* Queue
* Set
* List
* Ringbuffer
* FencedLock
* ISemaphore
* IAtomicLong
* IAtomicReference
* FlakeIdGenerator
* ICountdownLatch
* Cardinality Estimator
* PN Counter

Besides these, Hazelcast also offers the Replicated Map structure as
explained in the above *Standard utility collections* list.

[[loading-and-destroying-a-distributed-object]]
== Loading and Destroying a Distributed Object

Hazelcast offers a `get` method for most of its distributed objects. To load an object,
first create a Hazelcast instance and then use the related `get` method on this instance.
Following example code snippet creates an Hazelcast instance and a map on this instance.

[source,java]
----
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
Map<Integer, String> customers = hazelcastInstance.getMap( "customers" );
----

As to the configuration of distributed object, Hazelcast uses the default settings
from the file `hazelcast.xml` that comes with your Hazelcast download. Of course,
you can provide an explicit configuration in this XML or programmatically according
to your needs. See the xref:configuration:understanding-configuration.adoc[Understanding Configuration section].

Note that, most of Hazelcast's distributed objects are created lazily, i.e., a distributed object
is created once the first operation accesses it.

If you want to use an object you loaded in other places, you can safely reload it using its
reference without creating a new Hazelcast instance (`customers` in the above example).

To destroy a Hazelcast distributed object, you can use the method `destroy`. This method clears
and releases all resources of the object. Therefore, you must use it with care since a reload
with the same object reference after the object is destroyed creates a new data structure without
an error. See the following example code where one of the queues are destroyed and the other
one is accessed.

[source,java]
----
include::{javasource}/MapMember.java[tag=mapmember]
----

If you start the `Member` above, the output is as shown below:

[source,shell]
----
q1.size: 1 q2.size:1
q1.size: 0 q2.size:0
----

As you see, no error is generated and a new queue resource is created.

Hazelcast is designed to create any distributed data structure whenever it is accessed,
i.e., whenever a call is made to the data structure. Therefore, keep in mind that a
data structure is recreated when you perform an operation on it even after you have destroyed it.

[[controlling-partitions]]
== Controlling Partitions

Hazelcast uses the name of a distributed object to determine which partition it will be put.
Let's load two queues as shown below:

[source,java]
----
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
IQueue q1 = hazelcastInstance.getQueue("q1");
IQueue q2 = hazelcastInstance.getQueue("q2");
----

Since these queues have different names, they will be placed into different partitions.
If you want to put these two into the same partition, you use the `@` symbol as shown below:

[source,java]
----
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
IQueue q1 = hazelcastInstance.getQueue("q1@foo");
IQueue q2 = hazelcastInstance.getQueue("q2@foo");
----

Now, these two queues will be put into the same partition whose partition key is `foo`.
Note that you can use the method `getPartitionKey` to learn the partition key of a distributed object.
It may be useful when you want to create an object in the same partition of an existing object.
See its usage as shown below:

[source,java]
----
String partitionKey = q1.getPartitionKey();
IQueue q3 = hazelcastInstance.getQueue("q3@"+partitionKey);
----

[[common-features-of-all-hazelcast-data-structures]]
== Common Features of all Hazelcast Data Structures

* If a member goes down, its backup replica (which holds the same data) dynamically
redistributes the data, including the ownership and locks on them, to the remaining
live members. As a result, there will not be any data loss.
* There is no single cluster master that can be a single point of failure.
Every member in the cluster has equal rights and responsibilities. No single member is
superior. There is no dependency on an external 'server' or 'master'.

[[example-distributed-object-code]]
== Example Distributed Object Code

Here is an example of how you can retrieve existing data structure instances
(map, queue, set, topic, etc.) and how you can listen for instance events,
such as an instance being created or destroyed.

[source,java]
----
include::{javasource}/ExampleDOL.java[tag=sampledol]
----