= Reading Map Metrics
:description: By default, you can read metrics for a given map, such as the primary and backup entry count, last update time, and locked entry count on each member of your cluster. You can access these statistics about either all map entries that are owned by a member or specific entries.

{description}

[[accessing-entry-statistics]]

== Getting Statistics about All Map Entries

To get statistics for all map entries that are owned by a member, use the
`getLocalMapStats()` method of the Java member API (xref:overview:topology.adoc[embedded mode]). This method returns data only if the `statistics-enabled` element is set to `true`, which is the default. If this element is set to `false`, statistics are not available in the xref:management-center:ROOT:index.adoc[Hazelcast Management Center] or the API.

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <map name="myMap">
        <statistics-enabled>true</statistics-enabled>
    </map>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  map:
    myMap:
      statistics-enabled: true
----
====


[source,java]
----
LocalMapStats mapStatistics = myMap.getLocalMapStats();
System.out.println( "Number of entries owned by this member = "
    + mapStatistics.getOwnedEntryCount() );
----

NOTE: If you need cluster-wide map statistics, you can
get the local map statistics from all members of the cluster and combine them. Alternatively, you can see all map statistics in xref:management-center:monitor-imdg:monitor-dds.adoc#managing-maps[Hazelcast Management Center].

== Getting Statistics about a Specific Map Entry

To get statistics for a specific map entry, you can use the `getEntryView(key)` method of one of the following available client libraries.
To use this method, the map must have its `per-entry-statistics-enabled` element set to `true`.

This method returns the following statistics:

[cols="m,a"]
|===
|Statistic|Desscription

|cost
|Cost (in bytes) of the entry.

|creationTime
|Creation time of the entry.

|expirationTime
|Expiration time of the entry.

|hits
|Number of hits of the entry.

|key
|Key of the entry.

|lastAccessTime
|Last access time for the entry.

|lastStoredTime
|Last time the value was saved to a MapStore.

|lastUpdateTime
|Last time the value was updated.

|maxIdle
|Last set max idle time in milliseconds.

|ttl
|Last set time-to-live in milliseconds.

|value
|Value of the entry.

|version
|Version of the entry.

|===

[tabs] 
==== 
XML:: 
+ 
-- 
[source,xml]
----
<hazelcast>
    ...
    <map name="myMap">
        <per-entry-statistics-enabled>true</per-entry-statistics-enabled>
    </map>
    ...
</hazelcast>
----
--

YAML::
+
[source,yaml]
----
hazelcast:
  map:
    myMap:
      per-entry-statistics-enabled: true
----
====

[tabs] 
==== 
Java (Embedded Mode):: 
+ 
--
[source,java]
----
HazelcastInstance hz = Hazelcast.newHazelcastInstance();

EntryView entry = hz.getMap( "quotes" ).getEntryView( "key" );

System.out.println ( "size in memory  : " + entry.getCost() );
System.out.println ( "creationTime    : " + entry.getCreationTime() );
System.out.println ( "expirationTime  : " + entry.getExpirationTime() );
System.out.println ( "number of hits  : " + entry.getHits() );
System.out.println ( "lastAccessedTime: " + entry.getLastAccessTime() );
System.out.println ( "lastUpdateTime  : " + entry.getLastUpdateTime() );
System.out.println ( "version         : " + entry.getVersion() );
System.out.println ( "key             : " + entry.getKey() );
System.out.println ( "value           : " + entry.getValue() );
----
--
Java (Client/Server Mode):: 
+ 
--
[source,java]
----
HazelcastInstance hz = HazelcastClient.newHazelcastClient();

EntryView entry = hz.getMap( "map" ).getEntryView( "key" );

System.out.println ( "size in memory  : " + entry.getCost() );
System.out.println ( "creationTime    : " + entry.getCreationTime() );
System.out.println ( "expirationTime  : " + entry.getExpirationTime() );
System.out.println ( "number of hits  : " + entry.getHits() );
System.out.println ( "lastAccessedTime: " + entry.getLastAccessTime() );
System.out.println ( "lastUpdateTime  : " + entry.getLastUpdateTime() );
System.out.println ( "version         : " + entry.getVersion() );
System.out.println ( "key             : " + entry.getKey() );
System.out.println ( "value           : " + entry.getValue() );
----
--
C++:: 
+ 
--

[source,cpp]
----

----
--

C Sharp:: 
+ 
-- 
[source,cs]
----
var capitalcities = hzInstance.GetMap("capitals");
capitalcities.put( 1, "Tokyo" );
capitalcities.put( 2, "Paris" );
capitalcities.put( 3, "Washington" );
capitalcities.put( 4, "Ankara" );
capitalcities.put( 5, "Brussels" );
----
--

Node.js:: 
+ 
-- 
[source,javascript]
----
const client = await Client.newHazelcastClient();

const map = await client.getMap('map');

const entryView = await map.getEntryView('key');

console.log(`size in memory  :  ${entry.cost}`);
console.log(`creationTime    : ${entry.creationTime}`);
console.log(`expirationTime  : ${entry.expirationTime}`);
console.log(`number of hits  : ${entry.hits}`);
console.log(`lastAccessedTime: ${entry.lastAccessTime}`);
console.log(`lastUpdateTime  : ${entry.lastUpdateTime}`);
console.log(`version         : ${entry.version}`);
console.log(`key             : ${entry.key}`);
console.log(`value           : ${entry.value}`);
----
--

Python:: 
+ 
--
[source,python]
----
client = hazelcast.HazelcastClient()
entry = client.get_map("map").get_entry_view("key").result()
print("size in memory  :", entry.cost)
print("creationTime    :", entry.creation_time)
print("expirationTime  :", entry.expiration_time)
print("number of hits  :", entry.hits)
print("lastAccessedTime:", entry.last_access_time)
print("lastUpdateTime  :", entry.last_update_time)
print("version         :", entry.version)
print("key             :", entry.key)
print("value           :", entry.value)
----
--
Go:: 
+ 
-- 
[source,go]
----
capitalcities, _ := hzInstance.GetMap("capitals")
capitalcities.Put( 1, "Tokyo" );
capitalcities.Put( 2, "Paris" );
capitalcities.Put( 3, "Washington" );
capitalcities.Put( 4, "Ankara" );
capitalcities.Put( 5, "Brussels" );
----
--
====

