= Reading Data From a Map
:description:  

[reading-a-map]]

{description}

== Retrieving Entries

You can retrieve map data using the following methods:

* `map.get(K)` - returns the value associated with the specified key
* `map.values` - returns a collection of all values in the map
* `map.keySet` - returns a set of all keys in the map
* `map.entrySet` - returns a set of all key/value pairs in the map
* `map.containsKey()`  and `map.containsValue()` - checks whether specified key or value is contained in the map and returns a true or false

All of these methods return data to your application without altering the contents of the map itself. 

In the code sample below, we're using the `map.entrySet` method to retrieve the entire contents of the map, then printing out each entry.

(Need code samples of using entrySet for node.js)

[tabs] 
==== 
Java:: 
+ 
--
[source,java]
----
  for (Map.Entry<Integer, String> entry : myMap.entrySet()) {
      System.out.println(entry.getKey() + " " + entry.getValue());


----
--
C++:: 
+ 
-- 
[source,cpp]
----
    for (const auto &entry : my_map->entry_set<int, std::string>().get()) {
        std::cout << entry.first << " " << entry.second << std::endl;
    }

----
--

C Sharp:: 
+ 
-- 
[source,cs]
----
foreach (var (key, value) in await map.GetEntriesAsync())
{
  Console.WriteLine(key + " " + value);
}

----
--

Node.js:: 
+ 
-- 
[source,javascript]
----
const capitalcities = await hzClient.getMap('capitals');

----
--
Python:: 
+ 
-- 
[source,python]
----
for key, value in my_map.entry_set():
    print(key, value)

----
--
Go:: 
+ 
-- 
[source,go]
----
// error handling is omitted for brevity
entries, _ := myMap.GetEntrySet()
for _, entry := range entries {
    fmt.Printf("%d %s\n", entry.Key, entry.Value)
}

----
--
====
NOTE: The set returned by this method is not in any particular order. Because the map is distributed across multiple Hazelcast nodes, the set will be assembled in the order in which cluster members respond to the request. 

== Queries

A map query allows you to retrieve a subset of the map data that matches one or more criteria. You specify this criteria in a predicate. Hazelcast provides two query formats (Criteria API and SQL-like Predicates) to embed in your application code, as well as direct SQL query support. 

Hazelcast runs queries as a distributed process. You can read the details of query operations and formatting in the xref:query:distributed-query.adoc[Distributed Query] section of the documentation.

== Reading Data into Pipelines

In-memory data can be used as a source for a Jet engine pipeline, or as a store for enrichment data. In this case, the instructions for data retrieval are part of the Jet pipline code. Refer to the Jet engine documentation for details on using in-memory maps as either pipeline sources or as enrichment sources. 

== Optimizing Data Retrieval

If you are doing frequent `map.get` operations from a relatively static map, you can employ the Near Cache feature to improve performance. Near Cache creates a copy of the map data locally on the client, and all `map.get` operations are executed on the cached data rather than the map in the Hazelcast cluster. The cluster will synchronize the cached data with the cluster data at regular, configured intervals. This solution is most suitable when your maps do not change often and when the map operations are mostly reads. Refer to the xref:performance:near-cache.adoc[Near Cache] section of the documentation for details on operations, configuration, and limitations of this feature.
