= Reading Data From a Map
:description:  

[reading-a-map]]

{description}

== Retrieving Individual Entries

== Queries



== Reading Data into Jet

In-memory data can be used as a source for a Jet pipeline, or as a store for enrichment data. In this case, the instructions for data retrieval are part of the Jet pipline code. Refer to the Jet documentation for details on using in-memory maps as either pipeline sources or as enrichment sources. 

== Optimizing Data Retrieval

If you are doing frequent `map.get` operations from a relatively static map, you can employ the Near Cache feature to improve performance. Near Cache creates a copy of the map data locally on the client, and all `map.get` operations are executed on the cached data rather than the map in the Hazelcast cluster. The cluster will synchronize the cached data with the cluster data at regular, configured intervals. This solution is most suitable when your maps do not change often and when the map operations are mostly reads. Refer to the xref:performance:nearcache.adoc[Near Cache] section of the documentation for details on operations, configuration, and limitations of this feature.
