= Updating Map Entries
:description: Maps are not static. You can update or remove individual map entries, a group of map entries, or the entire map.

[[updating-map-entries]]

{description}

== Updating Individual Entries

The simplest way to update a map entry is with the `map.put` method. If the key already exists in the map, Hazelcast will replace the stored value with the new value. If the key does not exist in the map, Hazelcast will add it to the map. This method returns a copy of the old value stored in the map. 

[tabs] 
==== 
Java:: 
+ 
--
[source,java]
----
Map<Integer, String> countries = hzClient.getMap( "countries" );
countries.put( 1, "Japan" );
countries.put( 2, "France" );
countries.put( 3, "USA" );
countries.put( 4, "Turkey" );
countries.put( 5, "Ukraine" );
----
--
C++:: 
+ 
-- 
[source,cpp]
----
IMap countries = hzClient.getMap("countries");
countries.put( 1, "Japan" );
countries.put( 2, "France" );
countries.put( 3, "USA" );
countries.put( 4, "Turkey" );
countries.put( 5, "Ukraine" );
----
--

C Sharp:: 
+ 
-- 
[source,cs]
----
var countries = hzClient.GetMap("countries");
countries.put( 1, "Japan" );
countries.put( 2, "France" );
countries.put( 3, "USA" );
countries.put( 4, "Turkey" );
countries.put( 5, "Ukraine" );
----
--

Node.js:: 
+ 
-- 
[source,javascript]
----
const countries = await hzClient.getMap('countries');
await countries.put( 1, "Japan" );
await countries.put( 2, "France" );
await countries.put( 3, "USA" );
await countries.put( 4, "Turkey" );
await countries.put( 5, "Ukraine" );
----
--
Python:: 
+ 
-- 
[source,python]
----
countries = hzClient.get_map("countries").blocking()
countries.put( 1, "Japan" )
countries.put( 2, "France" )
countries.put( 3, "USA" )
countries.put( 4, "Turkey" )
countries.put( 5, "Ukraine" )
----
--
Go:: 
+ 
-- 
[source,go]
----
countries, _ := hzClient.GetMap("countries")
countries.Put( 1, "Japan" );
countries.Put( 2, "France" );
countries.Put( 3, "USA" );
countries.Put( 4, "Turkey" );
countries.Put( 5, "Ukraine" );
----
--
====

If you want to ensure that you do not overwrite any existing values, use the `map.putIfAbsent` method. With this method, the put will only succeed if the value associated with the specified key is null. 

Another update method is `map.replace`. This method returns a `true` (replacement succeeded) or `false` (replacement failed) rather than a map entry value. If the map entry does not already exist, this method will fail. 

There are two variants of `map.replace`. In the first, you specify the key and the new value. As long as the key exists, the new value will overwrite any old value. In the second, you specify the key and a specific old value, then the new value. This will only succeed if the specified old value matches what is actually stored in the map. The following code sample attempts to update the map "countries" we created above. Results are explained in the callouts.

[tabs] 
==== 
Java:: 
+ 
--
[source,java]
----
countries.replace( 1, "Korea" ); // <1>
countries.replace( 2, "France", "Spain" ); // <2>
countries.replace( 3, "United States", "Canada"); // <3>
----
<1> Replaces any value for key 1 with "Korea". Key exists, so returns `true`. 
<2> Replaces only if current value is "France". Value is "France", so returns `true`.
<3> Replaces only if current value is "United States". Value is "USA", so replace fails and returns `false.`

----
--
C++:: 
+ 
-- 
[source,cpp]
----
countries.replace( 1, "Korea" ); // <1>
countries.replace( 2, "France" ); // <2>
countries.replace( 3, "United States", "Canada" ); // <3>
----
<1> Replaces any value for key 1 with "Korea". Key exists, so returns `true`. 
<2> Replaces only if current value is "France". Value is "France", so returns `true`.
<3> Replaces only if current value is "United States". Value is "USA", so replace fails and returns `false.`
----
--

C Sharp:: 
+ 
-- 
[source,cs]
----
countries.replace( 1, "Korea" ); // <1>
countries.replace( 2, "France", "Spain" ); // <2>
countries.replace( 3, "United States", "Canada" ); // <3>
----
<1> Replaces any value for key 1 with "Korea". Key exists, so returns `true`. 
<2> Replaces only if current value is "France". Value is "France", so returns `true`.
<3> Replaces only if current value is "United States". Value is "USA", so replace fails and returns `false.`
----
--

Node.js:: 
+ 
-- 
[source,javascript]
----
await countries.replace( 1, "Korea" ); // <1>
await countries.replace( 2, "France", "Spain" ); // <2>
await countries.replace( 3, "United States", "Canada" ); // <3>
----
<1> Replaces any value for key 1 with "Korea". Key exists, so returns `true`. 
<2> Replaces only if current value is "France". Value is "France", so returns `true`.
<3> Replaces only if current value is "United States". Value is "USA", so replace fails and returns `false.`
----
--
Python:: 
+ 
-- 
[source,python]
----
countries.replace( 1, "Korea" ) # <1>
countries.replace( 2, "France", "Spain" ) # <2>
countries.replace( 3, "United States", "Canada" ) # <3>
----
<1> Replaces any value for key 1 with "Korea". Key exists, so returns `true`. 
<2> Replaces only if current value is "France". Value is "France", so returns `true`.
<3> Replaces only if current value is "United States". Value is "USA", so replace fails and returns `false.`
----
--
Go:: 
+ 
-- 
[source,go]
----
countries.Put( 1, "Korea" ); // <1>
countries.Put( 2, "France", "Spain" ); // <2>
countries.Put( 3, "United States", "Canada" ); // <3>
----
<1> Replaces any value for key 1 with "Korea". Key exists, so returns `true`. 
<2> Replaces only if current value is "France". Value is "France", so returns `true`.
<3> Replaces only if current value is "United States". Value is "USA", so replace fails and returns `false.`
----
--
====


== Batch Updates 

The `map.putAll` and `map.replaceAll` methods can be used to update multiple entries in a map. These methods can be used to copy one map to another, or in conjunction with MapLoader to load data into a map from an external source. See the xref:working-with-external-data.adoc[Working with External Data] page for more details.

== Entry Processor

The Hazelcast Entry Processor is an efficient way to perform updates to a map. Rather than retrieving an individual entry, modifying it at the client, then putting the modified data back into the map, Hazelcast performs the update operations within the cluster. This feature is covered in the xref:computing:entry-processor.adoc[Entry Processor] section of the documentation.

== Deleting Individual Map Entries

There are several methods availble for removing individual entries from a map. The method you choose depends on the results you want to achieve, as described in the following table.

[cols="1,1,1,1"]
|===
|Method
|Erase in-memory
|Erase from data store
|Returns

|`map.evict(K)`
|Y
|N
|true/false

|`map.delete(K)`
|Y
|Y
|true/false

|`map.clear(K)`
|Y
|Y
|void

|`map.remove(K)`
|Y
|Y
|removed value

|===

If you are not working with a external data store using the MapLoader feature, `map.evict` and `map.delete` have the same effect.

== Deleting Selected Map Entries

To remove multiple entries from a map, you can use `map.removeAll` in combination with a predicate to remove entries that match a given criteria. If you are working with an external data store, this will remove the entries from both the in-memory store and the external store. Unlike the `map.remove` method, this does not return the removed values. 

In the example below, assume a data set called Students. The data set has a field called GradYear. We want to remove all records of students with a GradYear of 2020.

[tabs] 
==== 
Java:: 
+ 
--
[source,java]
----
Map<Integer, Student> studentmap = hzClient.getMap( "studentmap" );

----
--
C++:: 
+ 
-- 
[source,cpp]
----
IMap studentmap = hzClient.getMap("studentmap");

----
--

C Sharp:: 
+ 
-- 
[source,cs]
----
var studentmap = hzClient.GetMap("studentmap");

----
--

Node.js:: 
+ 
-- 
[source,javascript]
----
const studentmap = await hzClient.getMap('studentmap');

----
--
Python:: 
+ 
-- 
[source,python]
----
studentmap = hzClient.get_map("studentmap").blocking()

----
--
Go:: 
+ 
-- 
[source,go]
----
studentmap, _ := hzClient.GetMap("studentmap")

----
--
====

== Removing Map Data or Map Data Structure

You can remove all data from a map or remove the map itself. See the table below for the different methods and their results. 

[cols="1,1"]
|===
|Method
|Result

|`map.evictAll`
|Removes all unlocked map entries from in-memory storage

Map data structure remains in memory

|`map.clear`
|Removes all map entries from in-memory storage

Removes all entries from external data store

Map data structure remains in memory

|`map.destroy`
|Removes data structure from in-memory storage

Has no effect on external data store


|===






