
= WAN Replication
[[wan-replication]]

[blue]*Hazelcast IMDG Enterprise Feature*

There could be cases where you need to synchronize multiple Hazelcast clusters to the same state. Hazelcast WAN Replication allows you to keep multiple Hazelcast clusters in sync by replicating their state over WAN environments such as the Internet.

Imagine you have different data centers in New York, London and Tokyo each running an independent Hazelcast cluster. Every cluster would be operating at native speed in their own LAN (Local Area Network), but you also want some or all record sets in these clusters to be replicated to each other: updates in the Tokyo cluster should also replicate to London and New York and updates in the New York cluster are to be synchronized to the Tokyo and London clusters.

This section explains how you can replicate the state of your clusters over Wide Area Network (WAN) through Hazelcast WAN Replication.

NOTE:  You can download the white paper Hazelcast on AWS: Best Practices for Deployment at https://hazelcast.com/resources/amazon-ec2-deployment-guide/[Hazelcast.com].

NOTE: To be able to use the REST calls related to WAN Replication mentioned in the following sections, you need to enable the WAN REST endpoint group. See the xref:management:rest-endpoint-groups.adoc[Using the REST Endpoint Groups section] for details