= Discovery Mechanisms
[[discovery-mechanisms]]

A Hazelcast cluster is a network of cluster members that run Hazelcast.
Cluster members  automatically join together to form a cluster. This automatic
joining takes place with various discovery mechanisms that the cluster members
use to find each other.

Please note that, after a cluster is formed, communication between cluster members
is always via TCP/IP, regardless of the discovery mechanism used.

Hazelcast uses the following discovery mechanisms.

NOTE: See the https://hazelcast.com/resources/hazelcast-deployment-operations-guide/[Hazelcast IMDG Deployment and Operations Guide^]
for advices on the best discovery mechanism to use.

[[tcp]]
== TCP

You can configure Hazelcast to be a full TCP/IP cluster. See the
xref:discovering-by-tcp.adoc[Discovering Members by TCP section for configuration details.

[[multicast]]
== Multicast

With this mechanism, Hazelcast allows cluster members to find each other
using the multicast communication. See the
xref:discovering-by-multicast.adoc[Discovering Members by Multicast section].

If you prefer to use this mechanism, make sure that your network is secure.
Since multicast packets are being broadcasted, any member from anywhere can join
the cluster with the appropriate cluster name, so you have less control on the cluster.

Note also that if User Datagram Protocol (UDP) is blocked, as it is for most of the production environments,
discovering with multicast does not work.

[[aws-cloud-discovery]]
== AWS Cloud Discovery

Hazelcast supports EC2 auto-discovery. It is useful when you do not want to provide or you cannot provide the list of possible IP addresses. This discovery feature is provided as a Hazelcast plugin. See its https://github.com/hazelcast/hazelcast-aws/blob/master/README.md[documentation] for information on configuring and using it.

[[azure-cloud-discovery]]
== Azure Cloud Discovery

Hazelcast offers a discovery strategy for your Hazelcast applications running on Azure. This strategy provides all of your Hazelcast instances by returning the virtual machines within your Azure resource group that are tagged with a specified value. This discovery feature is provided as a Hazelcast plugin. See its https://github.com/hazelcast/hazelcast-azure/blob/master/README.md[documentation] for information on configuring and using it.

[[gcp-cloud-discovery]]
== GCP Cloud Discovery

Hazelcast supports discovering members in the https://cloud.google.com/compute/[GCP Compute Engine] environment. You can easily configure Hazelcast members discovery, WAN replication, and Hazelcast Client to work seamlessly on the native GCP VM Instances. This discovery feature is provided as a Hazelcast plugin. See its https://github.com/hazelcast/hazelcast-gcp/blob/master/README.md[documentation] for information on configuring and using it.

[[apache-jclous-cloud-discovery]]
== Apache jclouds® Cloud Discovery

Hazelcast members and native clients support jclouds® for discovery. This mechanism allows applications to be deployed in various cloud infrastructure ecosystems in an infrastructure-agnostic way. This discovery feature is provided as a Hazelcast plugin. See its https://github.com/hazelcast/hazelcast-jclouds/blob/master/README.md[documentation] for information on configuring and using it.

[[kubernetes-cloud-discovery]]
== Kubernetes Cloud Discovery

Kubernetes is an open source system for automating deployment, scaling and management of containerized applications. Hazelcast provides Kubernetes discovery mechanism that looks for IP addresses of other members by resolving the requests against a Kubernetes Service Discovery system. It supports two different options of resolving against the discovery registry: (i) a request to the REST API, (ii) DNS Lookup against a given DNS service name. This discovery feature is provided as a Hazelcast plugin. See its https://github.com/hazelcast/hazelcast-kubernetes[documentation] for information on configuring and using it.

[[eureka-cloud-discovery]]
== Eureka Cloud Discovery

Eureka is a REST based service that is primarily used in the AWS cloud for locating services for the purpose of load balancing and failover of middle-tier servers. Hazelcast supports Eureka V1 discovery; Hazelcast members within EC2 Virtual Private Cloud can discover each other using this mechanism. This discovery feature is provided as a Hazelcast plugin. See its https://github.com/hazelcast/hazelcast-eureka[documentation].

[[zookeeper-cloud-discovery]]
== Zookeeper Cloud Discovery

This discovery mechanism provides a service based discovery strategy by using Apache Curator to communicate with your Zookeeper server. You can use this plugin with Discovery SPI enabled applications. This is provided as a Hazelcast plugin. See its https://github.com/hazelcast/hazelcast-zookeeper/blob/master/README.md[documentation] for information on configuring and using it.