= Discovery Mechanisms
[[discovery-mechanisms]]

A Hazelcast cluster is a network of cluster members that run Hazelcast.
Cluster members  automatically join together to form a cluster. This automatic
joining takes place with various discovery mechanisms that the cluster members
use to find each other.

Please note that, after a cluster is formed, communication between cluster members
is always via TCP/IP, regardless of the discovery mechanism used.

Hazelcast uses the following discovery mechanisms.

NOTE: See the https://hazelcast.com/resources/hazelcast-deployment-operations-guide/[Hazelcast IMDG Deployment and Operations Guide^]
for advices on the best discovery mechanism to use.

[[auto-detection]]
== Auto Detection

By default, Hazelcast tries to automatically detect the applicable discovery mechanism based on the runtime environment.

Note that using Auto Detection is not recommended for production. Note also that if Hazelcast finds no applicable
discovery mechanism, then it falls back to <<multicast, Multicast>>.

See the <<discovering-members-auto-detection, Discovering Members by Auto Detection section>> for more details.

[[tcp]]
=== TCP

You can configure Hazelcast to be a full TCP/IP cluster. See the
<<discovering-members-by-tcp, Discovering Members by TCP section>> for configuration details.

[[multicast]]
== Multicast

Multicast mechanism is not recommended for production since UDP is often
blocked in production environments and other discovery mechanisms are more definite.

With this mechanism, Hazelcast allows cluster members to find each other
using multicast communication. See the
<<discovering-members-by-multicast, Discovering Members by Multicast section>>.

[[aws-cloud-discovery]]
== AWS Cloud Discovery

Hazelcast supports EC2/ECS auto-discovery. It is useful when you
do not want to provide or you cannot provide the list of possible
IP addresses. See the <<hazelcast-cloud-discovery-plugins-aws, Cloud Discovery Plugins: Hazelcast AWS section>>.

[[azure-cloud-discovery]]
== Azure Cloud Discovery

Hazelcast offers a discovery strategy for your Hazelcast applications
running on Azure. See the <<hazelcast-cloud-discovery-plugins-azure, Cloud Discovery Plugins: Hazelcast Azure section>>.

[[gcp-cloud-discovery]]
== GCP Cloud Discovery

Hazelcast supports discovering members in the https://cloud.google.com/compute/[GCP Compute Engine^]
environment. You can easily configure Hazelcast members discovery, WAN replication,
and Hazelcast Client to work seamlessly on the native GCP VM Instances.
This discovery feature is provided as a Hazelcast plugin.
See the <<hazelcast-cloud-discovery-plugins-gcp, Cloud Discovery Plugins: Hazelcast GCP section>>.

[[kubernetes-cloud-discovery]]
== Kubernetes Cloud Discovery

Hazelcast provides Kubernetes discovery mechanism that looks for IP addresses of members.
See the <<hazelcast-cloud-discovery-plugins-kubernetes, Cloud Discovery Plugins: Hazelcast Kubernetes section>>.

[[eureka-cloud-discovery]]
== Eureka Cloud Discovery

Hazelcast supports the Eureka V1 discovery.
See the <<hazelcast-cloud-discovery-plugins-eureka, Cloud Discovery Plugins: Hazelcast Eureka section>>.

[[zookeeper-cloud-discovery]]
== Zookeeper Cloud Discovery

This discovery mechanism provides a service based discovery strategy by using
Apache Curator to communicate with your Zookeeper server.
See the <<hazelcast-cloud-discovery-plugins-zookeeper, Cloud Discovery Plugins: Hazelcast Zookeeper section>>.

[[hazelcast-for-pcf]]
== Hazelcast for Tanzu VMware

Using a clickable Hazelcast Tile for VMWare (former Pivotal Cloud Foundry), you can
deploy your Hazelcast cluster on PCF. This feature is provided as a Hazelcast
plugin.
See the <<deploying-on-pivotal-cloud-foundry, Deploying in VMware Tanzu section>>.