= Management Center

Hazelcast Management Center enables you to monitor and manage your cluster members running Hazelcast.
In addition to monitoring the overall state of your clusters, you can also analyze and browse your
data structures in detail, update map configurations and take thread dumps from members.
You can run scripts (JavaScript, Groovy, etc.) and commands on your members with its scripting and console modules.

See the xref:management-center::index.adoc[Management Center documentation]
for its usage details.

== Toggle Scripting Support

The support for script execution is disabled by default. The reason is security.
Script engines allow to access the underlying system on the members (files and other resources).
Scripts access the system, on which the member runs, with permissions of the running user.

Scripting can be allowed or prevented by specifying the `scripting-enabled` attribute of
the `management-center` element within the Hazelcast member configuration file, as shown below:

[source,xml]
----
<hazelcast>
    ...
    <management-center enabled="true" scripting-enabled="false">
        http://localhost:8080/hazelcast-mancenter
    </management-center>
    ...
</hazelcast>
----

Note that the https://jcp.org/en/jsr/detail?id=223[JSR 223^] API is used in Hazelcast IMDG to support scripting.

== Clustered JMX and REST via Management Center

[blue]*Hazelcast IMDG Enterprise*

See the {mc-docs}[Hazelcast Management Center Documentation^]
for information on Clustered JMX and Clustered REST (via Management Center) features.