= Encryption

Hazelcast offers features which allow to reach a required privacy on
communication level by enabling encryption. Encryption is based on
http://java.sun.com/javase/6/docs/technotes/guides/security/crypto/CryptoSpec.html[Java Cryptography Architecture^] (JCA).

There are two different encryption features:

* TLS protocol
** transport level encryption
** supported by members and clients
** TCP-only, i.e., Multicast join messages are not encrypted)
** see the <<tlsssl, TLS/SSL section>> for details
* Symmetric encryption for Hazelcast member protocol
** only supported by the members; communication with clients is not encrypted
** multicast join messages are encrypted, too

The preferred and recommended feature is the TLS protocol as it's a
standard way how to protect communication on transport level.

Symmetric encryption for Hazelcast member protocol can be configured with cipher algorithms implemented by security providers and accessed through Java Cryptography Architecture.
Check documentation of your Java version to learn about supported algorithm
names. The following are some examples:

* `AES`
* `PBEWithMD5AndDES`
* `DES/ECB/PKCS5Padding`
* `Blowfish`

Hazelcast uses `MD5` message-digest algorithm as the cryptographic hash function. You can also use the salting process by giving a salt and password which are then concatenated and processed with `MD5`, and the resulting output is stored with the salt.

In symmetric encryption, each member uses the same key, so the key is shared. Here is an example configuration for symmetric encryption.


[source,xml]
----
<hazelcast>
    ...
    <network>
        <symmetric-encryption enabled="true">
            <algorithm>AES</algorithm>
            <salt>thesalt</salt>
            <password>thepass</password>
            <iteration-count>175</iteration-count>
        </symmetric-encryption>
    </network>
    ...
</hazelcast>
----

You set the encryption algorithm, the salt value to use for generating the secret key, the password to use when generating the secret key and the iteration count to use when generating the secret key. You also need to set `enabled` to true. Note that all members should have the same encryption configuration.