= Starting the Member and Client
[[starting-the-member-and-client]]

Having installed Hazelcast, you can get started.

In this short tutorial, you perform the following activities:

. Create a simple Java application using the Hazelcast distributed map and queue.
. Run our application twice to have a cluster with two members (JVMs).
. Connect to our cluster from another Java application by using the Hazelcast Native Java Client API.

Let's begin.


* The following code starts the first Hazelcast member and creates and uses the `customers` map and queue.
+
[source,java]
----
include::{javasource}/GettingStartedMember.java[tag=startmember]
----
+
* Run this `GettingStarted` class a second time to get the second member
started. The members form a cluster and the output is similar to the following.
+
```
Members {size:2, ver:2} [
    Member [127.0.0.1]:5701 - e40081de-056a-4ae5-8ffe-632caf8a6cf1 this
    Member [127.0.0.1]:5702 - 93e82109-16bf-4b16-9c87-f4a6d0873080
]
```
+
Here, you can see the size of your cluster (`size`) and member list version (`ver`). The member list version is incremented when changes happen to the cluster, e.g., a member leaving from or joining to the cluster.
+
The above member list format is introduced with Hazelcast 3.9. You can enable the legacy member list format,  which was used for the releases before Hazelcast 3.9, using the system property `hazelcast.legacy.memberlist.format.enabled`. See the xref:ROOT:system-properties.adoc[System Properties appendix]. The following is an example for the legacy member list format:
+
```
Members [2] {
    Member [127.0.0.1]:5701 - c1ccc8d4-a549-4bff-bf46-9213e14a9fd2 this
    Member [127.0.0.1]:5702 - 33a82dbf-85d6-4780-b9cf-e47d42fb89d4
}
```
+
* Now, add the `hazelcast-client-`*`<version>`*`.jar` library to your classpath.
This is required to use a Hazelcast client.
* The following code starts a Hazelcast Client, connects to our cluster,
and prints the size of the `customers` map.
+
[source,java]
----
public class GettingStartedClient {
    public static void main( String[] args ) {
        ClientConfig clientConfig = new ClientConfig();
        HazelcastInstance client = HazelcastClient.newHazelcastClient( clientConfig );
        IMap map = client.getMap( "customers" );
        System.out.println( "Map Size:" + map.size() );
    }
}
----
+
* When you run it, you see the client properly connecting to the cluster
and printing the map size as **3**.

Hazelcast also offers a tool, **Management Center**, that enables you to monitor your cluster.
You can download it from Hazelcast website's https://hazelcast.org/imdg/download/#hazelcast-management-center[download page].
You can use it to monitor your maps, queues and other distributed data structures and members. Please
see the https://docs.hazelcast.com/management-center/latest/getting-started.html[Hazelcast Management Center Reference Manual] for usage explanations.

By default, Hazelcast uses multicast to discover other members that can form a cluster.  If you are
working with other Hazelcast developers on the same network, you may find yourself joining their
clusters under the default settings.  Hazelcast provides a way to segregate clusters within the same
network when using multicast. See the xref:clusters:creating-clusters.adoc#creating-cluster-groups[Creating Cluster Groups section]
for more information.  Alternatively, if you do not wish to use the default multicast mechanism,
you can provide a fixed list of IP addresses that are allowed to join.

NOTE: Multicast mechanism is not recommended for production since UDP is often blocked in production environments and other discovery mechanisms are more definite. See the xref:clusters:discovery-mechanisms.adoc[Discovery Mechanisms section].

NOTE: You can also check the video tutorials https://hazelcast.org/imdg/get-started/[here].
