= Using the Scripts in the Package
[[using-the-scripts-in-the-package]]

This chapter explains how to install Hazelcast and start
a Hazelcast member and client. It describes the executable
files in the download package and also provides the fundamentals
for configuring Hazelcast and its deployment options.

When you download and extract the Hazelcast ZIP or TAR.GZ package, you will
see the following scripts under the `/bin` folder that provide basic
functionalities for member and cluster management.

The following are the names and descriptions of each script:

* `start.sh` / `start.bat`: Starts a Hazelcast member with default
configuration in the working directory.
* `stop.sh` / `stop.bat`: Stops the Hazelcast member that was started
in the current working directory.
+
NOTE: `start.sh` / `start.bat` scripts lets you start one Hazelcast instance
per folder. To start a new instance, please unzip Hazelcast ZIP or TAR.GZ
package in a new folder.
+
NOTE: You can also use the start scripts to deploy your own library to a
Hazelcast member. See the xref:clusters:deploying-code-from-clients.adoc#adding-user-library-to-classpath[Adding User
Library to CLASSPATH section].
* `cluster.sh`: Provides basic functionalities for cluster management,
such as getting and changing the cluster state, shutting down the cluster
or forcing the cluster to clean its persisted data and make a fresh start.
See the xref:management:cluster-utilities.adoc#using-the-script-cluster-sh[Using the Script cluster.sh section]
to learn the usage of this script.
* `cp-subsystem.sh`: Provides access to the CP subsystem management APIs
using the REST interface.
See the xref:cp-subsystem:management.adoc#cp-subsystem-management-apis[CP Subsystem Management APIs section].
* `healthcheck.sh`: Provides basic information about your clusters
such as the state and size.
See the xref:management:health-check-monitoring.adoc#health-check-script[Using the healthcheck.sh Script section].