# This workflow will take the contents of the content branches and build the production documentation site

name: Build production site

on:
  push:
    branches: [ 'v/*', archived-versions ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build
      run: curl -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_ID }}

